#!/usr/bin/env python3
from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parent
REPORTS = ROOT / "reports"
PUBLISH = ROOT / "publish_dashboard"

FILES = {
    "portfolio_dashboard.html": "portfolio_dashboard.html",
    "portfolio_analytics.html": "portfolio_analytics.html",
    "portfolio_business_intelligence.html": "portfolio_business_intelligence.html",
    "portfolio_financial_diagnostics.html": "portfolio_financial_diagnostics.html",
}


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def main() -> int:
    if PUBLISH.exists():
        shutil.rmtree(PUBLISH)
    PUBLISH.mkdir(exist_ok=True)
    for src_name, dst_name in FILES.items():
        src = REPORTS / src_name
        if not src.exists():
            raise FileNotFoundError(f"Missing generated report: {src}")
        shutil.copy2(src, PUBLISH / dst_name)

    write_text(
        PUBLISH / "index.html",
        """<!doctype html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="refresh" content="0; url=portfolio_dashboard.html">
  <title>Official Portfolio Dashboard</title>
</head>
<body>
  <a href="portfolio_dashboard.html">فتح داشبورد المحفظة المعتمدة</a>
</body>
</html>
""",
    )
    write_text(PUBLISH / ".nojekyll", "")
    write_text(
        PUBLISH / "robots.txt",
        """User-agent: *
Disallow: /
""",
    )
    write_text(
        PUBLISH / "README.txt",
        """This folder is the static GitHub Pages package.
It contains only rendered dashboard pages, not Python source files.

Approved default dashboard:
portfolio_dashboard.html

Approved investment engine:
V3.1 Hybrid with approved daily-high next-session trailing stop (0.5 percent)

Approved market data source:
EODHD EOD-IntraDay All World, five-minute regular-session bars.

Execution model:
Targets and existing stops execute on five-minute bars.
The raised trailing stop is computed after a completed trading session from its high,
then becomes executable in the following trading session.

Official simulation start:
2021-01-01

Methodology note:
The 0.5 percent stop step was selected using 2021 data.
For conservative evaluation, read results beginning from 2022-01-01.

Comparison pages are kept in the reports folder only and are not published here.

Generated by:

python update_github_pages.py
""",
    )
    print(f"Prepared GitHub Pages folder: {PUBLISH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
