#!/usr/bin/env python3
from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parent
REPORTS = ROOT / "reports"
PUBLISH = ROOT / "publish_dashboard"

FILES = {
    "paper_portfolio_v2_dashboard.html": "paper_portfolio_v2_dashboard.html",
    "paper_portfolio_v2_analytics.html": "paper_portfolio_v2_analytics.html",
    "strategy_v2_dashboard.html": "strategy_v2_dashboard.html",
}


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def main() -> int:
    if PUBLISH.exists():
        shutil.rmtree(PUBLISH)
    PUBLISH.mkdir(exist_ok=True)
    for src_name, dst_name in FILES.items():
        src = REPORTS / src_name
        if not src.exists():
            raise FileNotFoundError(f"Missing generated report: {src}")
        shutil.copy2(src, PUBLISH / dst_name)

    write_text(
        PUBLISH / "index.html",
        """<!doctype html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="refresh" content="0; url=paper_portfolio_v2_dashboard.html">
  <title>V2 Dashboard</title>
</head>
<body>
  <a href="paper_portfolio_v2_dashboard.html">فتح الداشبورد</a>
</body>
</html>
""",
    )
    write_text(PUBLISH / ".nojekyll", "")
    write_text(
        PUBLISH / "robots.txt",
        """User-agent: *
Disallow: /
""",
    )
    write_text(
        PUBLISH / "README.txt",
        """This folder is the static GitHub Pages package.
It contains only rendered dashboard pages, not Python source files.
Generated by:

python update_github_pages_v2.py
""",
    )
    print(f"Prepared GitHub Pages folder: {PUBLISH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
